# Generated by Django 5.1.5 on 2025-01-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Komedia'), (0, 'Inne'), (3, 'Sci-fi'), (4, 'Drama'), (1, 'Horro')], default=0),
        ),
    ]
