# Generated by Django 5.1.5 on 2025-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0002_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (2, 'Komedia'), (4, 'Drama'), (1, 'Horro'), (3, 'Sci-fi')], default=0),
        ),
    ]
