# Generated by Django 5.1.5 on 2025-01-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmweb', '0009_ocena_user_alter_dodatkoweinfo_gatunek'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dodatkoweinfo',
            name='gatunek',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Inne'), (3, 'Sci-fi'), (4, 'Drama'), (1, 'Horro'), (2, 'Komedia')], default=0),
        ),
    ]
